dependencies:
  pre:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install -y gcc-6 g++-6 gfortran-6 cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20

compile:
  override:
    - cmake --version && g++ --version
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
test:
  override:
    - ctest --test-regex unit
