version: 2
jobs:
  working_directory: ~/dgswemv2
#  build:
#  environment:
#    Boost_ROOT: /home/ubuntu/boost_1_63_0_install
#    INSTALL_ROOT: /home/ubuntu/install
#    LD_LIBRARY_PATH: /home/ubuntu/boost_1_63_0_install/lib:/home/ubuntu/install/lib

dependencies:
  pre:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get update
    - sudo apt-get install -y gcc-6 g++-6 gfortran-6 cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20

compile:
  override:
    - cmake --version && g++ --version
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j8
test:
  override:
    - ctest --test-regex unit

#dist: trusty
#sudo: required
#language:
#- cpp
#compiler:
#- g++
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-5
#    - cmake
#before_install:
#- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#- sudo apt-get update -qq

#install:
#- sudo apt-get install -qq g++-5

#script:
#- sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
#- export CXX=/usr/bin/g++-5
#- ctest --test-regex unit
